CREATE TABLE restaurant(
  id uuid NOT NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  name_jp VARCHAR(200),
  description TEXT,
  description_jp TEXT,
  city VARCHAR(200),
  city_jp VARCHAR(200),
  area VARCHAR(200),
  area_jp VARCHAR(200),
  address VARCHAR(600),
  address_jp VARCHAR(600),
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,  
  average_cost INTEGER,
  average_user_rating DOUBLE PRECISION,  
  featured BOOLEAN,  
  cover_image_link TEXT,
  all_image_links TEXT,
  website VARCHAR(200),
  instagram_handle VARCHAR(200),
  facebook_url VARCHAR(200),
  phone VARCHAR(30),
  email VARCHAR(40),  
  location GEOMETRY,
  create_time TIMESTAMP WITH TIME ZONE,
  update_time TIMESTAMP WITH TIME ZONE,
  closed_flag BOOLEAN
);